sudo: required
language: bash
services:
  - docker

before_install:
  - docker build .

script:
  - docker run –d –p 82:8080 springimg 

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  - docker push springimg