sudo: required

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t springimg .
      - docker images
      - docker tag springimg $DOCKER_USERNAME/springimg
      - docker push $DOCKER_USERNAME/springimg