version: 0.2

phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - mvn clean install
artifacts:
  files:
  - target/*.war
  discard-paths: yes
